# Markdown语法

https://laravel-china.org/topics/621/you-will-be-able-to-master-these-markdown-grammars

# 数组和标量之间的运算_Notes

不需要编写循环即可对数据执行批量运算,
矢量化(Vectorization),
大小相等的数组之间的任何算术运算都会讲运算应用到元素级,
不同大小的数组之间的运算叫做广播(broadcasting)

In [21]:
#常用的引用
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [3]:
arr+arr

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]])

In [5]:
arr*arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

# 基本的索引和切片 

和Python基本的索引和切片操作基本一致

In [8]:
Arr = np.arange(10)
Arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

索引操作, 从0开始

In [9]:
Arr[5]

5

切片操作,arr[n.m]，从arr[n]开始到arr[m-1]结束！

In [10]:
Arr[5:8]

array([5, 6, 7])

切片操作并赋值，切片内的元素全部被赋予同一值,多维数组的情况下，所有最底层的元素也都会被赋予相同的值

In [12]:
Arr[5:8] = 12
Arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

**跟列表最重要的区别在于，数组切片是原始数组的视图，这意味着数组不会被复制，在视图上的任何修改都会直接反映到原数组上,主要是因为NumPy主要是为了处理大数据，如果在操作是进行复制，会占用大量内存和花费很长时间，影响处理效率！！！**

In [13]:
arr_slice = Arr[1:3]
arr_slice[1] = 12345
Arr

array([    0,     1, 12345,     3,     4,    12,    12,    12,     8,     9])

多数数组中，索引和切片有更多的用途，更实用！

In [17]:
arr2D = np.arange(9).reshape((3,3))
arr2D

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

2维数组的单个索引为一个数组，双索引为一个元素，更高维度依次类推！

In [15]:
arr2D[1]

array([3, 4, 5])

In [16]:
arr2D[1][2]

5

In [20]:
arr2D[1,2] #另一种多维数组索引的方式

5

# 切片索引